:tada: Amnesia 移植
GraiaProject/Ariadne pull request #156
Opened 2022-05-13 04:50 UTC by BlueGlassBlock

**更改说明**
参见 #124 

**向后兼容性**
破坏性更改

2022-05-20 15:21 UTC, GreyElaina commented
TODO: MessageChain implementation switch to Amnesia's implementation.

2022-05-22 02:44 UTC, GreyElaina requested changes

2022-05-22 04:15 UTC, BlueGlassBlock commented on src/graia/ariadne/connection/connector.py
> +            return
这样 income 会有大量 warning log 吧，不过可以 sentinel 就是了

2022-05-22 04:24 UTC, BlueGlassBlock commented on src/graia/ariadne/instance.py
> +    }
把 `Ariadne.create` 的 `Scheduler` 啦 `Saya` 啦 `Behaviour` 啦全扔到这里，可能要声明 private

2022-05-22 06:51 UTC, BlueGlassBlock commented on src/graia/ariadne/instance.py
> +        cls._patch_launch_manager()
但是用户应该有添加 AiohttpService 之类的权利

2022-05-22 06:52 UTC, BlueGlassBlock commented on src/graia/ariadne/instance.py
> +        cls._patch_launch_manager()
而且 `_patch_launch_manager` 是幂等的

2022-05-22 06:57 UTC, BlueGlassBlock commented on src/graia/ariadne/instance.py
> +    launch_manager: ClassVar[LaunchManager] = LaunchManager()
主要是 Broadcast 与 Loop 的信息是与 Service 耦合的

2022-05-22 08:38 UTC, GreyElaina commented on src/graia/ariadne/app.py
> +            cls._launch_task = asyncio.create_task(cls.launch_manager.launch(), name="amnesia-launch")
请直接调用 `LaunchManager.launch`.

2022-05-22 08:46 UTC, GreyElaina commented on src/graia/ariadne/app.py
> +            return cls.instances[connection]
wait....
我这里建议是像 `Ariadne.current(account)` 这样的.

2022-05-22 08:47 UTC, GreyElaina commented on src/graia/ariadne/app.py
> +    def current(cls) -> "Ariadne":
就如 `__new__` 中我说的一样, 加一个 `Ariadne.current(account)` 的用法.

2022-05-22 08:47 UTC, GreyElaina commented on src/graia/ariadne/app.py
> +        return cls(cls.default_account)
转接到 `Ariadne.current(cls.default_account)`

2022-05-22 09:11 UTC, GreyElaina commented on src/graia/ariadne/model/relationship.py
> +        perm_map: Dict[str, str] = {
建议常量化

2022-05-22 09:16 UTC, GreyElaina commented on src/graia/ariadne/service.py
> +        self.broadcast = Broadcast(loop=loop)
从参数中或者什么其他的对方获取..
所以我想的就是让你在 init 的时候去创建 service 并注入到 mgr(如果没有的话, 有就检查各项的唯一性)

2022-05-22 09:21 UTC, GreyElaina commented on src/graia/ariadne/instance.py
> +    }
不是, 算了到时候再说...反正生命周期上都是单例也没啥问题

2022-05-22 09:22 UTC, GreyElaina commented on src/graia/ariadne/instance.py
> +    launch_manager: ClassVar[LaunchManager] = LaunchManager()
那就在 init 里面实例化 service 并注入 launch manager(如果不存在这样的service, 否则获取.)

2022-05-22 09:23 UTC, GreyElaina commented on src/graia/ariadne/instance.py
> +        cls._patch_launch_manager()
...这是要引用外部的实例/设施

2022-05-22 09:26 UTC, GreyElaina commented on src/graia/ariadne/connection/connector.py
> +            return
大量倒不至于...可以放到 develop/debug 模式下面启用然后 production 下面不显示就好了.  
主要是我觉得风控那么严重, 那么就有一定需要去支持这种模式, 应该可以称作 "功能即服务" 吗?  
总之这个 low priority, 可以提到 issue 里面去.

2022-05-28 00:00 UTC, GreyElaina reviewed
Rolling Review Complete.

2022-05-30 14:31 UTC, BlueGlassBlock commented
记得别手贱 squash merge 了

2022-05-31 15:17 UTC, GreyElaina commented
痛苦起来了

2022-06-01 13:21 UTC, BlueGlassBlock commented
现在大概算 feature lock 了
等待 amnesia 和 launart publish

2022-06-01 13:21 UTC, BlueGlassBlock commented
@GreyElaina

2022-06-02 04:27 UTC, GreyElaina commented
先等我回去把statv独立出来。。大概还要这周末

2022-06-02 05:30 UTC, GreyElaina requested changes

2022-06-02 05:30 UTC, GreyElaina commented on docs/basic/background.md
> +    如果你想要使用多个账号的话, 注意每个账号都会触发一次 `ApplicationLaunched` 和 `ApplicationShutdowned` 事件.
换成 AccountAvailable / AccountUnavailable 更好

2022-06-02 05:30 UTC, GreyElaina commented on docs/basic/configuration.md
> +`LogConfig` 是字典的子类, 里面的键都是 [`MiraiEvent`][graia.ariadne.event.MiraiEvent] 的子类,
TypedDict?

2022-06-02 05:30 UTC, GreyElaina commented on docs/quickstart.md
> -## adapter 的单独配置，键名与 adapters 项配置相同
不建议：至少需要提一下要怎么改port 因为8080太常见了

2022-06-02 06:09 UTC, BlueGlassBlock commented on migrate_src/migrator.py
> +MAPPING: Dict[str, str] = {
这个就是简单的 replace function call 而已

2022-06-02 06:09 UTC, BlueGlassBlock commented on migrate_src/migrator.py
> +MAPPING: Dict[str, str] = {
不需要替换模块

2022-06-02 16:21 UTC, BlueGlassBlock commented on docs/basic/configuration.md
> +`LogConfig` 是字典的子类, 里面的键都是 [`MiraiEvent`][graia.ariadne.event.MiraiEvent] 的子类,
nope, TypedDict 能做的差远了

2022-06-03 05:10 UTC, GreyElaina approved these changes
初步审核通过。
建议：把你那堆 conn 写成 launart 的 Launchable 试试看

2022-06-03 13:16 UTC, GreyElaina commented
Statv 的实现在 https://gist.github.com/GreyElaina/3a6aa458fb5c394fc0d82437b6c066b9

2022-06-06 15:07 UTC, GreyElaina commented on src/graia/ariadne/service.py
> +            await self.prepare()
这里理论上 Never 了.

2022-06-07 05:29 UTC, merged