Add Alconna
GraiaProject/Ariadne pull request #28
Opened 2021-11-25 07:42 UTC by Little-LinNian

make some change in alconna of cesloi,make it can be use in Ariadne

2021-11-25 10:30 UTC, BlueGlassBlock commented on guide/docs/advance/alconna.md
> +![Example](https://i.loli.net/2021/11/25/xGMhXAaFT1qDEk8.png)
不要使用图床。放到文件夹里。

2021-11-25 10:31 UTC, BlueGlassBlock commented on src/graia/ariadne/message/parser/alconna.py
> +if __name__ == "__main__":
我不大喜欢把 test 放到 __main__ 块里。

2021-11-25 10:32 UTC, BlueGlassBlock commented on guide/docs/advance/alconna.md
> +解析时，先判断命令头(即 headers + command),再判断options与main argument, 这里options与main argument在输入指令时是不分先后的
Subcommand 呢？

2021-11-25 10:32 UTC, BlueGlassBlock commented on guide/docs/advance/alconna.md
> +# Alconna - Command Analysis
I hate typos.

2021-11-25 10:41 UTC, BlueGlassBlock commented on src/graia/ariadne/message/parser/alconna.py
> +from graia.ariadne.event.message import MessageEvent
用相对导入。

2021-11-25 10:41 UTC, BlueGlassBlock commented on guide/docs/advance/alconna.md
> +
`Alconna` 调用得这么长？而且似乎没有 type hint 啊。

2021-11-26 00:51 UTC, Little-LinNian commented
好，我周末整

2021-11-26 01:11 UTC, Little-LinNian commented on src/graia/ariadne/message/parser/alconna.py
> +from graia.ariadne.event.message import MessageEvent
![image](https://user-images.githubusercontent.com/65386393/143512502-f1c7d1a6-b6dd-4cd5-bd49-fd7790a311a1.png)
Like this(?

2021-11-26 01:12 UTC, Little-LinNian commented on src/graia/ariadne/message/parser/alconna.py
> +if __name__ == "__main__":
![image](https://user-images.githubusercontent.com/65386393/143512580-b8fd95e8-7730-4a53-931d-329fe0452a17.png)
Removed

2021-11-26 01:18 UTC, Little-LinNian commented on src/graia/ariadne/message/parser/alconna.py
> +if __name__ == "__main__":
![image](https://user-images.githubusercontent.com/65386393/143512884-ba4f5747-c08d-4b41-b650-660459f6678e.png)
add this

2021-11-26 15:04 UTC, GreyElaina commented
看的我血压有点高
我明天再review一遍

2021-11-27 11:21 UTC, GreyElaina commented on guide/docs/advance/alconna.md
> +```
恕我直言, 这段大部分都是不必要的, 请突出重点.

比如:

```python
from graia.ariadne.message.parser.alconna import (
    AlconnaParser,
    Alconna,
    Arpamar,
    Option,
    AnyStr,
)  # 必须从这里导入AnyStr，不能从typing中导入


ddd = Alconna(
    headers=["#"],  # 命令头
    command="点歌",  # 命令主体
    options=[Option("歌名", song_name=AnyStr), Option("歌手", singer_name=AnyStr)],  # 可选参数
)
@app.broadcast.receiver(FriendMessage, dispatchers=[AlconnaParser(alconna=ddd)])
async def friend_message_listener(app: Ariadne, friend: Friend, arpamar: Arpamar):
    if arpamar.has("歌名"):
        await app.sendFriendMessage(
            friend, MessageChain.create(Plain(arpamar.get_option_first_value("歌名")))
        )
    if arpamar.has("歌手"):
        await app.sendFriendMessage(
            friend, MessageChain.create(Plain(arpamar.get_option_first_value("歌手")))
        )
```

2021-11-27 11:22 UTC, GreyElaina commented on guide/docs/advance/alconna.md
> +```
@BlueGlassBlock 我个人希望其他的文档也可以这样只突出必要的重点

2021-11-27 11:25 UTC, GreyElaina commented on guide/docs/advance/alconna.md
> + - `main_argument` : 主参数，填入后当且仅当命令中含有该参数时才会成功解析
请遵循 [中文文案排版指北](https://github.com/sparanoid/chinese-copywriting-guidelines/).

2021-11-27 11:28 UTC, GreyElaina commented on src/graia/ariadne/message/parser/alconna.py
> +                                    ] = _rest_text
@BlueGlassBlock ...我觉得你可以考虑一下把 black 的 max-line-length 调到 110 附近?

2021-11-27 11:30 UTC, GreyElaina commented on src/graia/ariadne/message/parser/alconna.py
> +            del interface.broadcast.decorator_interface.local_storage["arpamar"]
对于 BCC 0.14.0 及以上版本, DecoratorInterface 的 local_storage 与整个执行流程共享同一个生命周期,
所以手动的清除是不必要的.
顺便一提, 我不建议使用 DeI 的 local_storage, 可能会引发潜在的难缠问题.

2021-11-27 11:32 UTC, GreyElaina requested changes
以上, 请酌情根据修改意见进行适当的修改.

2021-11-28 03:14 UTC, GreyElaina commented on src/graia/ariadne/message/parser/alconna.py
> +            del interface.broadcast.decorator_interface.local_storage["arpamar"]
于 0.14.3 中, 我已经把 local_storage 改成置于 exec ctx 内.

2021-11-28 03:16 UTC, BlueGlassBlock commented on src/graia/ariadne/message/parser/alconna.py
> +            del interface.broadcast.decorator_interface.local_storage["arpamar"]
但是 Ariadne 的 bcc deps 还是 `>= 0.12.1 with exceptions`

2021-11-28 05:41 UTC, RF-Tar-Railt commented on guide/docs/advance/alconna.md
> +解析时，先判断命令头(即 headers + command),再判断options与main argument, 这里options与main argument在输入指令时是不分先后的
Subcommand与Option都是options的，但是按程序逻辑来讲顺序是main-arg，Option，Subcommand

2021-11-28 05:41 UTC, RF-Tar-Railt commented on src/graia/ariadne/message/parser/alconna.py
> +                return True
there is a little bug...
update with lasted Alconna  [`c5f2288`](https://github.com/RF-Tar-Railt/Cesloi-Alconna/commit/c5f2288718ad6b18aeaec4c24ef05d855ddf74f8#diff-bb012d64de22456b65147c1230ae7b5509d31f4c01186952b9c780e8ff961bb5)

2021-11-28 05:50 UTC, RF-Tar-Railt commented on guide/docs/advance/alconna.md
> +
maybe better
```python
# example:   !点歌 歌名 大地 歌手 Beyond
ddd = Alconna(
    headers=["!"],  # 命令头
    command="点歌",  # 命令主体
    options=[  # 可选参数
        Option("歌名", song_name=AnyStr),
        Option("歌手", singer_name=AnyStr)
    ], 
)
```

2021-11-28 06:15 UTC, RF-Tar-Railt requested changes

2021-11-28 06:15 UTC, RF-Tar-Railt commented on guide/docs/advance/alconna.md
> +        )
maybe better:
```python
if arpamar.matched:
    if arpamar.has("歌名"):
        await app.sendFriendMessage(
            friend, MessageChain.create(arpamar.get("歌名").get("song_name"))
        )
    if arpamar.has("歌手"):
        await app.sendFriendMessage(
            friend, MessageChain.create(arpamar.get("歌手").get("singer_name"))
        )
```

2021-11-29 05:30 UTC, RF-Tar-Railt commented on src/graia/ariadne/message/parser/alconna.py
> +                return True
> 
lasted Alconna [`6e619dd`](https://github.com/RF-Tar-Railt/Cesloi-Alconna/commit/6e619dda14a6e6d40aed782edab891055f239236#diff-bb012d64de22456b65147c1230ae7b5509d31f4c01186952b9c780e8ff961bb5)

2021-11-30 12:32 UTC, RF-Tar-Railt commented
changed with lasted Alconna [06a991c](https://github.com/RF-Tar-Railt/Cesloi-Alconna/commit/06a991ca343e1c21e5ebacdc8bdbdf535e38fcf8)

2021-12-01 04:44 UTC, BlueGlassBlock commented
@Little-LinNian 因为这个部分要经常与 `Alconna` 同步, 还是单独出来比较好
你可以 Fork from `Alconna` 之后再进行修改, 这样 `fetch and marge` 也方便后续更新。
加到 `Graiax` 里吧, 这个 `PR` 讨论也够长了.

2021-12-01 14:22 UTC, GreyElaina commented
但是我想给 avilla.console 用了。
@BlueGlassBlock

2021-12-02 10:41 UTC, BlueGlassBlock commented
@GreyElaina 

主要原因是 `Alconna` 是持续维护的, 独立出来是最好的方案（我不大想做持续更新 `Alconna` 的工作，后续有没有人持续帮忙跟进还是未知的）

当然维护周期足够长的话也可以接受.

Reopened as draft.

2021-12-02 10:46 UTC, BlueGlassBlock commented on guide/docs/advance/alconna.md
> +Alconna 表示想变得更~~可爱~~美观一点
似乎没什么必要，因为阅读这篇的人~~多半不知道 Alconna 是什么~~

2021-12-02 10:46 UTC, BlueGlassBlock commented on guide/docs/advance/alconna.md
> +# Alconna - 命令行式消息链处理器
考虑和 `Twilight` 区分开。

2021-12-02 10:46 UTC, BlueGlassBlock commented on guide/docs/advance/alconna.md
> +!!! warning "前言"
改成 `info`

2021-12-02 10:55 UTC, BlueGlassBlock requested changes
这个部分对 0.12.1 ~ 0.13 的 bcc 不兼容
要改就顺便改到 0.14+ only 得了

2021-12-05 13:50 UTC, RF-Tar-Railt commented
[Alconna for graia （without decorator）](https://github.com/RF-Tar-Railt/Cesloi-Alconna/blob/main/alconna/__init__.py)

2021-12-06 10:25 UTC, RF-Tar-Railt requested changes

2021-12-06 10:25 UTC, RF-Tar-Railt commented on src/graia/ariadne/message/parser/alconna.py
> +NonTextElement = TypeVar("NonTextElement")
this should be `Element` in graia.ariadne.message.element
like 
```python
from ..element import Element
NonTextElement = TypeVar("NonTextElement", bound=Element)
```
or replace `NonTextElement`  to `Element`

2021-12-07 15:27 UTC, RF-Tar-Railt commented
最新Alconna更新 [a89fe77](https://github.com/RF-Tar-Railt/Cesloi-Alconna/commit/a89fe7769a8bf22bb8555e99156025b29ceadee2)

2021-12-10 05:23 UTC, closed without merging