修改与添加文档
GraiaProject/Ariadne pull request #46
Opened 2021-12-07 15:29 UTC by ZhaoZuohong

[PR]

**更改说明**

* 修改 `type-hint` 的名字和内容
* 添加一篇 `custom-decorator`
* 修改 `msg-chain` 中的格式问题

**向后兼容性**

* 把 `type-hint` 改了，和原来不兼容

2021-12-08 04:27 UTC, BlueGlassBlock commented on guide/docs/basic/param-type.md
> +```
考虑使用 `tabs` 重写
另外 `MessageEvent` 是需要 `bypass` 支持的，需要指明

2021-12-08 04:28 UTC, BlueGlassBlock requested changes

2021-12-08 04:28 UTC, BlueGlassBlock commented on guide/docs/basic/param-type.md
> +其中 `app: Airadne` 参数, 即为前文通过 `app = Ariadne(......)` 创建的 Ariadne 对象; `message: MessageChain` 参数, 我们将在[消息链: 基础](/basic/msg-chain/)一节中进行介绍.
typo

2021-12-08 04:28 UTC, BlueGlassBlock commented on guide/docs/advance/custom-decorator.md
> +# 自定义消息链处理器
这应该放到 `advance/broadcast.md`

2021-12-08 04:32 UTC, BlueGlassBlock commented
另外顺便把 `basic/instance.md` 更新一下

2021-12-09 04:27 UTC, BlueGlassBlock commented
嗯，看来还是得我自己改

2021-12-09 04:27 UTC, closed without merging

2021-12-09 04:42 UTC, ZhaoZuohong commented
> 嗯，看来还是得我自己改

我还没来得及按照你的要求改好